import { Header } from '@/components/layout/header';
import { Providers } from '@/components/layout/providers';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body className={cn(inter.className, 'flex min-h-svh flex-col')}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
